default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: epets_development

test:
  <<: *default
  database: epets_test

production:
  <<: *default
  database: epets_production
  pool: <%= ENV.fetch('WEB_CONCURRENCY_MAX_THREADS') { 32 }.to_i %>
